ALTER TABLE project ADD COLUMN banner_url VARCHAR(1024);
ALTER TABLE project ADD COLUMN github_url VARCHAR(1024);
ALTER TABLE project ADD COLUMN website_url VARCHAR(1024);
ALTER TABLE project ADD COLUMN view_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE project ADD COLUMN love_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE project ADD COLUMN celebrate_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE project ADD COLUMN genius_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE project ADD COLUMN help_count BIGINT NOT NULL DEFAULT 0;
